//
// Copyright (c) 2015 University of Cambridge
// All rights reserved.
//
//
//  File:
//        nf_sume_pktgen_regs_defines.h
//
//  Description:
//        This file is automatically generated with header defines for the software
//
// This software was developed by Stanford University and the University of Cambridge Computer Laboratory
// under National Science Foundation under Grant No. CNS-0855268,
// the University of Cambridge Computer Laboratory under EPSRC INTERNET Project EP/H040536/1 and
// by the University of Cambridge Computer Laboratory under DARPA/AFRL contract FA8750-11-C-0249 ("MRC2"),
// as part of the DARPA MRC research programme.
//
// @NETFPGA_LICENSE_HEADER_START@
//
// Licensed to NetFPGA C.I.C. (NetFPGA) under one or more contributor
// license agreements.  See the NOTICE file distributed with this work for
// additional information regarding copyright ownership.  NetFPGA licenses this
// file to you under the NetFPGA Hardware-Software License, Version 1.0 (the
// "License"); you may not use this file except in compliance with the
// License.  You may obtain a copy of the License at:
//
//   http://www.netfpga-cic.org
//
// Unless required by applicable law or agreed to in writing, Work distributed
// under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations under the License.
//
// @NETFPGA_LICENSE_HEADER_END@
//

##########This text should be copied to the head file #############
   #Registers offset definitions

#define SUME_NF_SUME_PKTGEN_ID_0_OFFSET 0x0
#define SUME_NF_SUME_PKTGEN_ID_0_DEFAULT 0x0000DA11
#define SUME_NF_SUME_PKTGEN_ID_0_WIDTH 32
#define SUME_NF_SUME_PKTGEN_VERSION_0_OFFSET 0x4
#define SUME_NF_SUME_PKTGEN_VERSION_0_DEFAULT 0x1
#define SUME_NF_SUME_PKTGEN_VERSION_0_WIDTH 32
#define SUME_NF_SUME_PKTGEN_RESET_0_OFFSET 0x8
#define SUME_NF_SUME_PKTGEN_RESET_0_DEFAULT 0x0
#define SUME_NF_SUME_PKTGEN_RESET_0_WIDTH 16
#define SUME_NF_SUME_PKTGEN_FLIP_0_OFFSET 0xC
#define SUME_NF_SUME_PKTGEN_FLIP_0_DEFAULT 0x0
#define SUME_NF_SUME_PKTGEN_FLIP_0_WIDTH 32
#define SUME_NF_SUME_PKTGEN_DEBUG_0_OFFSET 0x10
#define SUME_NF_SUME_PKTGEN_DEBUG_0_DEFAULT 0x0
#define SUME_NF_SUME_PKTGEN_DEBUG_0_WIDTH 32
#define SUME_NF_SUME_PKTGEN_PKTIN_0_OFFSET 0x14
#define SUME_NF_SUME_PKTGEN_PKTIN_0_DEFAULT 0x0
#define SUME_NF_SUME_PKTGEN_PKTIN_0_WIDTH 32
#define SUME_NF_SUME_PKTGEN_PKTOUT_0_OFFSET 0x18
#define SUME_NF_SUME_PKTGEN_PKTOUT_0_DEFAULT 0x0
#define SUME_NF_SUME_PKTGEN_PKTOUT_0_WIDTH 32
#define SUME_NF_SUME_PKTGEN_TRIGGER_0_OFFSET 0x1C
#define SUME_NF_SUME_PKTGEN_TRIGGER_0_DEFAULT 0x1'b0
#define SUME_NF_SUME_PKTGEN_TRIGGER_0_WIDTH 1
#define SUME_NF_SUME_PKTGEN_SIZE_0_OFFSET 0x20
#define SUME_NF_SUME_PKTGEN_SIZE_0_DEFAULT 0x40080
#define SUME_NF_SUME_PKTGEN_SIZE_0_WIDTH 32
#define SUME_NF_SUME_PKTGEN_NUMPKTS_0_OFFSET 0x24
#define SUME_NF_SUME_PKTGEN_NUMPKTS_0_DEFAULT 0x1
#define SUME_NF_SUME_PKTGEN_NUMPKTS_0_WIDTH 32
#define SUME_NF_SUME_PKTGEN_GAP_0_OFFSET 0x28
#define SUME_NF_SUME_PKTGEN_GAP_0_DEFAULT 0x1
#define SUME_NF_SUME_PKTGEN_GAP_0_WIDTH 16
#define SUME_NF_SUME_PKTGEN_KEEP_0_OFFSET 0x2C
#define SUME_NF_SUME_PKTGEN_KEEP_0_DEFAULT 0xffffffff
#define SUME_NF_SUME_PKTGEN_KEEP_0_WIDTH 32

#define SUME_NF_SUME_PKTGEN_META0_0_OFFSET 0x30
#define SUME_NF_SUME_PKTGEN_META0_0_DEFAULT 0x0
#define SUME_NF_SUME_PKTGEN_META0_0_WIDTH 8

#define SUME_NF_SUME_PKTGEN_META1_0_OFFSET 0x34
#define SUME_NF_SUME_PKTGEN_META1_0_DEFAULT 0x0
#define SUME_NF_SUME_PKTGEN_META1_0_WIDTH 8

#define SUME_NF_SUME_PKTGEN_META2_0_OFFSET 0x38
#define SUME_NF_SUME_PKTGEN_META2_0_DEFAULT 0x0
#define SUME_NF_SUME_PKTGEN_META2_0_WIDTH 8

#define SUME_NF_SUME_PKTGEN_META3_0_OFFSET 0x3C
#define SUME_NF_SUME_PKTGEN_META3_0_DEFAULT 0x0
#define SUME_NF_SUME_PKTGEN_META3_0_WIDTH 8

#define SUME_NF_SUME_PKTGEN_META4_0_OFFSET 0x40
#define SUME_NF_SUME_PKTGEN_META4_0_DEFAULT 0x0
#define SUME_NF_SUME_PKTGEN_META4_0_WIDTH 8

#define SUME_NF_SUME_PKTGEN_META5_0_OFFSET 0x44
#define SUME_NF_SUME_PKTGEN_META5_0_DEFAULT 0x0
#define SUME_NF_SUME_PKTGEN_META5_0_WIDTH 8

#define SUME_NF_SUME_PKTGEN_META6_0_OFFSET 0x48
#define SUME_NF_SUME_PKTGEN_META6_0_DEFAULT 0x0
#define SUME_NF_SUME_PKTGEN_META6_0_WIDTH 8

#define SUME_NF_SUME_PKTGEN_META7_0_OFFSET 0x4C
#define SUME_NF_SUME_PKTGEN_META7_0_DEFAULT 0x0
#define SUME_NF_SUME_PKTGEN_META7_0_WIDTH 8

#define SUME_NF_SUME_PKTGEN_META8_0_OFFSET 0x50
#define SUME_NF_SUME_PKTGEN_META8_0_DEFAULT 0x0
#define SUME_NF_SUME_PKTGEN_META8_0_WIDTH 8

#define SUME_NF_SUME_PKTGEN_META9_0_OFFSET 0x54
#define SUME_NF_SUME_PKTGEN_META9_0_DEFAULT 0x0
#define SUME_NF_SUME_PKTGEN_META9_0_WIDTH 8

#define SUME_NF_SUME_PKTGEN_META10_0_OFFSET 0x58
#define SUME_NF_SUME_PKTGEN_META10_0_DEFAULT 0x0
#define SUME_NF_SUME_PKTGEN_META10_0_WIDTH 8

#define SUME_NF_SUME_PKTGEN_META11_0_OFFSET 0x5C
#define SUME_NF_SUME_PKTGEN_META11_0_DEFAULT 0x0
#define SUME_NF_SUME_PKTGEN_META11_0_WIDTH 8

#define SUME_NF_SUME_PKTGEN_META12_0_OFFSET 0x60
#define SUME_NF_SUME_PKTGEN_META12_0_DEFAULT 0x0
#define SUME_NF_SUME_PKTGEN_META12_0_WIDTH 8

#define SUME_NF_SUME_PKTGEN_META13_0_OFFSET 0x64
#define SUME_NF_SUME_PKTGEN_META13_0_DEFAULT 0x0
#define SUME_NF_SUME_PKTGEN_META13_0_WIDTH 8

#define SUME_NF_SUME_PKTGEN_META14_0_OFFSET 0x68
#define SUME_NF_SUME_PKTGEN_META14_0_DEFAULT 0x0
#define SUME_NF_SUME_PKTGEN_META14_0_WIDTH 8

#define SUME_NF_SUME_PKTGEN_META15_0_OFFSET 0x6C
#define SUME_NF_SUME_PKTGEN_META15_0_DEFAULT 0x0
#define SUME_NF_SUME_PKTGEN_META15_0_WIDTH 8
