//
// Copyright (c) 2015 University of Cambridge
// All rights reserved.
//
//
//  File:
//        nf_sume_pktgen_cpu_regs_defines.v
//
//  Module:
//        nf_sume_pktgen_cpu_regs_defines
//
//  Description:
//        This file is automatically generated with the registers defintions towards the CPU/Software
//
// This software was developed by Stanford University and the University of Cambridge Computer Laboratory
// under National Science Foundation under Grant No. CNS-0855268,
// the University of Cambridge Computer Laboratory under EPSRC INTERNET Project EP/H040536/1 and
// by the University of Cambridge Computer Laboratory under DARPA/AFRL contract FA8750-11-C-0249 ("MRC2"),
// as part of the DARPA MRC research programme.
//
// @NETFPGA_LICENSE_HEADER_START@
//
// Licensed to NetFPGA C.I.C. (NetFPGA) under one or more contributor
// license agreements.  See the NOTICE file distributed with this work for
// additional information regarding copyright ownership.  NetFPGA licenses this
// file to you under the NetFPGA Hardware-Software License, Version 1.0 (the
// "License"); you may not use this file except in compliance with the
// License.  You may obtain a copy of the License at:
//
//   http://www.netfpga-cic.org
//
// Unless required by applicable law or agreed to in writing, Work distributed
// under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations under the License.
//
// @NETFPGA_LICENSE_HEADER_END@
//


`define  REG_ID_BITS				31:0
`define  REG_ID_WIDTH				32
`define  REG_ID_DEFAULT				32'hABCDEF01
`define  REG_ID_ADDR				32'h0

`define  REG_VERSION_BITS				31:0
`define  REG_VERSION_WIDTH				32
`define  REG_VERSION_DEFAULT				32'h1
`define  REG_VERSION_ADDR				32'h4

`define  REG_RESET_BITS				15:0
`define  REG_RESET_WIDTH				16
`define  REG_RESET_DEFAULT				16'h0
`define  REG_RESET_ADDR				32'h8

`define  REG_FLIP_BITS				31:0
`define  REG_FLIP_WIDTH				32
`define  REG_FLIP_DEFAULT				32'h0
`define  REG_FLIP_ADDR				32'hC

`define  REG_DEBUG_BITS				31:0
`define  REG_DEBUG_WIDTH				32
`define  REG_DEBUG_DEFAULT				32'h0
`define  REG_DEBUG_ADDR				32'h10

`define  REG_PKTIN_BITS				31:0
`define  REG_PKTIN_WIDTH				32
`define  REG_PKTIN_DEFAULT				32'h0
`define  REG_PKTIN_ADDR				32'h14

`define  REG_PKTOUT_BITS				31:0
`define  REG_PKTOUT_WIDTH				32
`define  REG_PKTOUT_DEFAULT				32'h0
`define  REG_PKTOUT_ADDR				32'h18

`define  REG_TRIGGER_BITS				15:0
`define  REG_TRIGGER_WIDTH				16
`define  REG_TRIGGER_DEFAULT				16'h0
`define  REG_TRIGGER_ADDR				32'h1C

`define  REG_SIZE_BITS				31:0
`define  REG_SIZE_WIDTH				32
`define  REG_SIZE_DEFAULT				32'h40080
`define  REG_SIZE_ADDR				32'h20

`define  REG_NUMPKTS_BITS				31:0
`define  REG_NUMPKTS_WIDTH				32
`define  REG_NUMPKTS_DEFAULT				32'h1
`define  REG_NUMPKTS_ADDR				32'h24

`define  REG_GAP_BITS				15:0
`define  REG_GAP_WIDTH				16
`define  REG_GAP_DEFAULT				32'h1
`define  REG_GAP_ADDR				32'h28

`define  REG_KEEP_BITS				31:0
`define  REG_KEEP_WIDTH				32
`define  REG_KEEP_DEFAULT				32'hffffffff
`define  REG_KEEP_ADDR				32'h2C

`define  REG_META0_BITS				7:0
`define  REG_META0_WIDTH				8
`define  REG_META0_DEFAULT				8'h0
`define  REG_META0_ADDR				32'h30

`define  REG_META1_BITS				7:0
`define  REG_META1_WIDTH				8
`define  REG_META1_DEFAULT				8'h0
`define  REG_META1_ADDR				32'h34

`define  REG_META2_BITS				7:0
`define  REG_META2_WIDTH				8
`define  REG_META2_DEFAULT				8'h0
`define  REG_META2_ADDR				32'h38

`define  REG_META3_BITS				7:0
`define  REG_META3_WIDTH				8
`define  REG_META3_DEFAULT				8'h0
`define  REG_META3_ADDR				32'h3C

`define  REG_META4_BITS				7:0
`define  REG_META4_WIDTH				8
`define  REG_META4_DEFAULT				8'h0
`define  REG_META4_ADDR				32'h40

`define  REG_META5_BITS				7:0
`define  REG_META5_WIDTH				8
`define  REG_META5_DEFAULT				8'h0
`define  REG_META5_ADDR				32'h44

`define  REG_META6_BITS				7:0
`define  REG_META6_WIDTH				8
`define  REG_META6_DEFAULT				8'h0
`define  REG_META6_ADDR				32'h48

`define  REG_META7_BITS				7:0
`define  REG_META7_WIDTH				8
`define  REG_META7_DEFAULT				8'h0
`define  REG_META7_ADDR				32'h4C

`define  REG_META8_BITS				7:0
`define  REG_META8_WIDTH				8
`define  REG_META8_DEFAULT				8'h0
`define  REG_META8_ADDR				32'h50

`define  REG_META9_BITS				7:0
`define  REG_META9_WIDTH				8
`define  REG_META9_DEFAULT				8'h0
`define  REG_META9_ADDR				32'h54

`define  REG_META10_BITS				7:0
`define  REG_META10_WIDTH				8
`define  REG_META10_DEFAULT				8'h0
`define  REG_META10_ADDR				32'h58

`define  REG_META11_BITS				7:0
`define  REG_META11_WIDTH				8
`define  REG_META11_DEFAULT				8'h0
`define  REG_META11_ADDR				32'h5C

`define  REG_META12_BITS				7:0
`define  REG_META12_WIDTH				8
`define  REG_META12_DEFAULT				8'h0
`define  REG_META12_ADDR				32'h60

`define  REG_META13_BITS				7:0
`define  REG_META13_WIDTH				8
`define  REG_META13_DEFAULT				8'h0
`define  REG_META13_ADDR				32'h64

`define  REG_META14_BITS				7:0
`define  REG_META14_WIDTH				8
`define  REG_META14_DEFAULT				8'h0
`define  REG_META14_ADDR				32'h68

`define  REG_META15_BITS				7:0
`define  REG_META15_WIDTH				8
`define  REG_META15_DEFAULT				8'h0
`define  REG_META15_ADDR				32'h6C
